@startuml C4_Container
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(onlineBank, "Интернет-банк") {
  Container(ui, "UI", "ASP.NET MVC", "Форма депозита")
  Container(controller, "DepositController", "C#", "Валидация и отправка заявки в API")
  ContainerDb(bankDb, "MS SQL", "Хранение заявок и справочников")
}

System_Boundary(depositServiceSys, "Сервис «Депозиты»") {
  Container(depositAPI, "REST API", "C#", "Обработка заявок")
  Container(stakeStorage, "Хранилище ставок", "MS SQL", "Ставки по депозитам")
}

System(coreBanking, "АБС", "Oracle", "Создание депозита, хранение договоров")
System_Ext(smsGateway, "СМС-шлюз", "Отправка уведомлений клиенту")

Rel(ui, controller, "Отправка данных")
Rel(controller, depositAPI, "REST API вызов")
Rel(depositAPI, stakeStorage, "Запись / чтение ставок")
Rel(depositAPI, coreBanking, "Создание депозита")
Rel(depositAPI, smsGateway, "Отправка уведомлений", "HTTPS/XML")

@enduml